###########################
# Override default settings
###########################

# Project information
site_name:  Library
site_url: 

# Repository
repo_url: https://github.com/easyscience/
edit_uri: edit/develop/docs/

# Copyright
copyright: ©  

# Extra icons in the bottom right corner
extra:
  social:
    - icon:   # File: overrides/.icons/.svg
      link: 
      name:  Main Webpage
    - icon: fontawesome/brands/github  # Name as in Font Awesome
      link: https://github.com/easyscience/
      name:  Library Source Code on GitHub

##################
# Add new settings
##################

# Exclude files and folders from the global navigation
not_in_nav: |
  index.md
  user-guide/parameters

# Format and layout of the global navigation for the site
nav:
  - Introduction:
      - Introduction: introduction/index.md
  - Installation & Setup:
      - Installation & Setup: installation-and-setup/index.md
  - User Guide:
      - User Guide: user-guide/index.md
      - Analysis Workflow:
        - Analysis Workflow: user-guide/analysis-workflow/index.md
        - Project: user-guide/analysis-workflow/project.md
        - Sample Model: user-guide/analysis-workflow/model.md
        - Experiment: user-guide/analysis-workflow/experiment.md
        - Analysis: user-guide/analysis-workflow/analysis.md
        - Summary: user-guide/analysis-workflow/summary.md
  - Tutorials:
      - Tutorials: tutorials/index.md
  - API Reference:
      - API Reference: api-reference-reference/index.md
