###########################
# Override default settings
###########################

# Project information
site_name: EasyPeasy Library
site_url: https://easyscience.github.io/peasy-lib

# Repository
repo_url: https://github.com/easyscience/peasy-lib
edit_uri: edit/develop/docs/

# Copyright
copyright: © 2025 EasyPeasy

# Extra icons in the bottom right corner
extra:
  social:
    - icon: easypeasy  # File: overrides/.icons/easypeasy.svg
      link: https://easypeasy.org
    - icon: fontawesome/brands/github  # Name as in Font Awesome
      link: https://github.com/easyscience/peasy-lib

# Jupyter notebooks
plugins:
  - mkdocs-jupyter:
      execute_ignore:
        - '*emcee*.ipynb' # Ignore notebooks with 'emcee' in the name from execution

##################
# Add new settings
##################

# Exclude files and folders from the global navigation
not_in_nav: |
  index.md
  usage/dictionaries

# Format and layout of the global navigation for the site
nav:
  - Introduction:
      - Introduction: introduction/index.md
  - Installation & Setup:
      - Installation & Setup: installation/index.md
  - User Guide:
      - User Guide: usage/index.md
      - Terminology: usage/terminology.md
      - Getting Started: usage/getting-started.md
      - Workflow Steps:
        - Workflow Steps: usage/workflow-steps/index.md
        - Project: usage/workflow-steps/project.md
        - Model: usage/workflow-steps/model.md
        - Experiment: usage/workflow-steps/experiment.md
        - Analysis: usage/workflow-steps/analysis.md
        - Summary: usage/workflow-steps/summary.md
  - Hands-on Tutorials:
      - Hands-on Tutorials: tutorials/index.md
      - Basic Examples: []
      - Simulation: []
      - Fitting: []
      - Advanced fitting: []
      - Additional examples: []
  - API Reference:
      - API Reference: api/index.md
  - Contributing:
      - Contributing: contributing/index.md
