name: PR labels check

on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

permissions:
  pull-requests: read

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          add_comment: true
          mode: minimum
          count: 1
          labels: |
            [bot] release
            [scope] bug
            [scope] documentation
            [scope] enhancement
            [scope] maintenance
            [scope] significant
